build:
  image: default-bionic
  environment:
    php: 8.1.2
  dependencies:
    before:
      - >
        export COMPOSER_ROOT_VERSION=$(grep '"dev-master": ' composer.json | grep -P -o '[0-9]+.[0-9]+').x-dev
      - composer validate

filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
