filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
build:
  environment:
    php:
      version: 8.0
  dependencies:
    before:
      - export COMPOSER_ROOT_VERSION=$(/usr/bin/jq --arg key "dev-${SCRUTINIZER_BRANCH}" --raw-output '.["extra"]["branch-alias"][$key]' ${PATH_TO_COMPOSER_JSON_FILE})
  project_setup:
    override:
      - 'composer validate'
      - 'composer update --prefer-dist --no-interaction --no-progress'
  tests:
    override:
      - command: vendor/bin/phpunit --coverage-clover=clover.xml
        coverage:
          file: clover.xml
          format: php-clover
